CREATE TABLE Book_list (id INT PRIMARY KEY, name TEXT, rating INT);
INSERT INTO Book_list VALUES (1, "MY JOURNEY THROUGH POSTPARTUM DEPRESSION", 7.5);
INSERT INTO Book_list VALUES (2, "THINGS FALL APART", 9);
INSERT INTO Book_list VALUES (3, "SCARS OF LOVE", 8.3);
SELECT * FROM Book_list;
INSERT INTO Book_list VALUES (4, "THE SANDS OF TIME", 7), (5, "THE ENCHANTED TABLE", 8), (6, "NO SWEETNESS HERE", 7.2), 
(7, "GREEF CHILD", 6), (8, "THE GODS ARE NOT TO BLAME", 9), (9, "ANANSE IN THE LAND OF IDIOTS", 8);
SELECT * FROM Book_list;
INSERT INTO Book_list VALUES (10, "HOW TO READ A PERSON LIKE A BOOK", 8.1), (11, "SMART MONEY WOMAN", 7.2), (12, "SMART MONEY TRIBE", 8.5), 
(13, "HOW TO WIN FRIENDS AND INFLUENCE PEOPLE", 8), (14, "FOURTH DIMENSION", 8.8), (15, "PROPHECY", 8.3), (16, "A MAN OF THE PEOPLE",6),
(17, "A TIME TO KILL", 5), (18, "ME,EARL AND THE DYING GIRL", 6.7), (19, "THE DRUMMER BOY'S BATTLE", 8), (20, "FLORENCE NIGHTINGALE", 9),
 (21, "ROMEO AND JULIET", 6), (22, "AS YOU LIKE IT", 5), (23, "MACBETH", 7.8), (24, "THE OPIUM WAR", 7.9), (25, "RICH DAD POOR DAD", 6.5),
 (26, "A GUIDE TO INVESTING", 5.6), (27, "SPIRIT OF LEADERSHIP", 8.2), (28, "POWER OF YOUR MIND", 9), (29, "FULL CIRCLE", 7.4), (30, "PEGASUS", 5.8);
SELECT * FROM Book_list;